name: Bug report
description: Report a reproducible non-security bug
title: "bug: "
body:
  - type: markdown
    attributes:
      value: "Do not report security vulnerabilities here. Use private vulnerability reporting."
  - type: input
    id: app-version
    attributes:
      label: App version
    validations:
      required: true
  - type: input
    id: authentik-version
    attributes:
      label: authentik version
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction steps
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
