package dev.greyfoundry.authentik.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal val AuthentikBrandHighlight = Color(0xFFFD4B2D)

internal val AuthentikLightColorScheme =
    lightColorScheme(
        primary = Color(0xFF9C250E),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFDAD3),
        onPrimaryContainer = Color(0xFF8F1200),
        inversePrimary = Color(0xFFFFB4A4),
        secondary = Color(0xFF80543C),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFFFDBCA),
        onSecondaryContainer = Color(0xFF653D27),
        tertiary = Color(0xFF825422),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFFFDCBE),
        onTertiaryContainer = Color(0xFF663D0B),
        background = Color(0xFFFFF8F6),
        onBackground = Color(0xFF271815),
        surface = Color(0xFFFFF8F6),
        onSurface = Color(0xFF271815),
        surfaceVariant = Color(0xFFFDDBD4),
        onSurfaceVariant = Color(0xFF58413D),
        surfaceTint = Color(0xFF9C250E),
        inverseSurface = Color(0xFF3D2C29),
        inverseOnSurface = Color(0xFFFFEDE9),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF93000A),
        outline = Color(0xFF8C716C),
        outlineVariant = Color(0xFFE0BFB9),
        scrim = Color(0xFF000000),
        surfaceDim = Color(0xFFF0D4CE),
        surfaceBright = Color(0xFFFFF8F6),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFFFF0EE),
        surfaceContainer = Color(0xFFFFE9E5),
        surfaceContainerHigh = Color(0xFFFFE2DC),
        surfaceContainerHighest = Color(0xFFF9DCD7),
        primaryFixed = Color(0xFFFFDAD3),
        primaryFixedDim = Color(0xFFFFB4A4),
        onPrimaryFixed = Color(0xFF3F0400),
        onPrimaryFixedVariant = Color(0xFF8F1200),
        secondaryFixed = Color(0xFFFFDBCA),
        secondaryFixedDim = Color(0xFFF3BA9C),
        onSecondaryFixed = Color(0xFF311302),
        onSecondaryFixedVariant = Color(0xFF653D27),
        tertiaryFixed = Color(0xFFFFDCBE),
        tertiaryFixedDim = Color(0xFFF7BB7E),
        onTertiaryFixed = Color(0xFF2C1600),
        onTertiaryFixedVariant = Color(0xFF663D0B),
    )

internal val AuthentikDarkColorScheme =
    darkColorScheme(
        primary = Color(0xFFFFB4A4),
        onPrimary = Color(0xFF5F1608),
        primaryContainer = Color(0xFF8F1200),
        onPrimaryContainer = Color(0xFFFFDAD3),
        inversePrimary = Color(0xFF9C250E),
        secondary = Color(0xFFF3BA9C),
        onSecondary = Color(0xFF4A2713),
        secondaryContainer = Color(0xFF653D27),
        onSecondaryContainer = Color(0xFFFFDBCA),
        tertiary = Color(0xFFF7BB7E),
        onTertiary = Color(0xFF4A2800),
        tertiaryContainer = Color(0xFF663D0B),
        onTertiaryContainer = Color(0xFFFFDCBE),
        background = Color(0xFF1E100D),
        onBackground = Color(0xFFF9DCD7),
        surface = Color(0xFF1E100D),
        onSurface = Color(0xFFF9DCD7),
        surfaceVariant = Color(0xFF58413D),
        onSurfaceVariant = Color(0xFFE0BFB9),
        surfaceTint = Color(0xFFFFB4A4),
        inverseSurface = Color(0xFFF9DCD7),
        inverseOnSurface = Color(0xFF3D2C29),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        outline = Color(0xFFA78A85),
        outlineVariant = Color(0xFF58413D),
        scrim = Color(0xFF000000),
        surfaceDim = Color(0xFF1E100D),
        surfaceBright = Color(0xFF473531),
        surfaceContainerLowest = Color(0xFF180B08),
        surfaceContainerLow = Color(0xFF271815),
        surfaceContainer = Color(0xFF2B1C19),
        surfaceContainerHigh = Color(0xFF372623),
        surfaceContainerHighest = Color(0xFF42312D),
        primaryFixed = Color(0xFFFFDAD3),
        primaryFixedDim = Color(0xFFFFB4A4),
        onPrimaryFixed = Color(0xFF3F0400),
        onPrimaryFixedVariant = Color(0xFF8F1200),
        secondaryFixed = Color(0xFFFFDBCA),
        secondaryFixedDim = Color(0xFFF3BA9C),
        onSecondaryFixed = Color(0xFF311302),
        onSecondaryFixedVariant = Color(0xFF653D27),
        tertiaryFixed = Color(0xFFFFDCBE),
        tertiaryFixedDim = Color(0xFFF7BB7E),
        onTertiaryFixed = Color(0xFF2C1600),
        onTertiaryFixedVariant = Color(0xFF663D0B),
    )

internal val LightAuthentikExtendedColors =
    AuthentikExtendedColors(
        success = Color(0xFF2E6B3A),
        onSuccess = Color(0xFFFFFFFF),
        warning = Color(0xFF735C00),
        onWarning = Color(0xFFFFFFFF),
        info = Color(0xFF145EA8),
        onInfo = Color(0xFFFFFFFF),
        stale = Color(0xFF5D5F65),
        onStale = Color(0xFFFFFFFF),
    )

internal val DarkAuthentikExtendedColors =
    AuthentikExtendedColors(
        success = Color(0xFF86D993),
        onSuccess = Color(0xFF003914),
        warning = Color(0xFFE8C547),
        onWarning = Color(0xFF3C2F00),
        info = Color(0xFFA8C7FA),
        onInfo = Color(0xFF07305E),
        stale = Color(0xFFC5C6CC),
        onStale = Color(0xFF2E3035),
    )
